language: cpp

branches:
  except:
    - /^build@.*/

matrix:
  include:
    - os: linux
      dist: trusty
      env: TARGET=linux32
    - os: linux
      dist: trusty
      env: TARGET=linux64
    - os: osx
      env: TARGET=macosx64

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew install ant
        bash install-osx-jdk8.sh
    fi

before_script:
  - git clone --depth=1 https://bitbucket.org/chromiumembedded/java-cef.git $TRAVIS_BUILD_DIR/java-cef/src
  - echo "Running cmake..."
  - cd $TRAVIS_BUILD_DIR/java-cef/src
  - mkdir jcef_build
  - cd jcef_build
  - if [[ "$TARGET" == "linux32" ]]; then cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .. ; fi
  - if [[ "$TARGET" != "linux32" ]]; then cmake -G "Unix Makefiles" -DPROJECT_ARCH="x86_64" -DCMAKE_BUILD_TYPE=Release .. ; fi

script:
  - echo \ >> $TRAVIS_BUILD_DIR/java-cef/src/native/CefFrame_N.cpp
  - make -j4

before_deploy:
  - echo "Making distribution..."
  - cd $TRAVIS_BUILD_DIR/java-cef/src/tools
  - bash make_distrib.sh $TARGET
  - cd $TRAVIS_BUILD_DIR/java-cef/src/binary_distrib
  - 7z a jcef-${TARGET}-distribution.zip $TARGET
  - |
    git config --global user.email "builds@travis-ci.com"
    git config --global user.name "Travis CI"
    export GIT_TAG=build-travis@${TRAVIS_BRANCH}#${TRAVIS_BUILD_NUMBER}
    git tag ${GIT_TAG} -a -m "Generated tag from TravisCI build ${TRAVIS_BUILD_NUMBER}"
    git push --quiet https://${GITHUB_TOKEN}@github.com/Team-Fruit/java-cef-build ${GIT_TAG} > /dev/null 2>&1 || true

deploy:
  provider: releases
  prerelease: true
  api_key: ${GITHUB_TOKEN}
  file: $TRAVIS_BUILD_DIR/java-cef/src/binary_distrib/jcef-${TARGET}-distribution.zip
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    condition: '! "$TRAVIS_BRANCH" =~ ^(dev\\-|feature\\/).*$'

notifications:
  email: false