language: cpp

branches:
  except:
    - /^build@.*/

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ant; fi

before_script:
  - mkdir jcef && cd jcef
  - git clone https://bitbucket.org/chromiumembedded/java-cef.git src
  - cd src && mkdir jcef_build && cd jcef_build

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .. ; fi
  - if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then cmake -G "Unix Makefiles" -DPROJECT_ARCH="x86_64" -DCMAKE_BUILD_TYPE=Release .. ; fi
  - echo \ >> ../native/CefFrame_N.cpp
  - make -j4

before_deploy:
  - cd native/Release/ && zip -r ../../../../java-cef-native-${TRAVIS_OS_NAME}.zip ./ && cd ../../../../
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build@${TRAVIS_BRANCH}#${TRAVIS_BUILD_NUMBER}
  - git tag ${GIT_TAG} -a -m "Generated tag from TravisCI build ${TRAVIS_BUILD_NUMBER}"
  - git push --quiet https://${GITHUB_TOKEN}@github.com/Team-Fruit/java-cef-build ${GIT_TAG} > /dev/null 2>&1

deploy:
  provider: releases
  prerelease: true
  api_key: ${GITHUB_TOKEN}
  file: java-cef-native-${TRAVIS_OS_NAME}.zip
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    condition: '! "$TRAVIS_BRANCH" =~ ^(dev\\-|feature\\/).*$'